   public static class NacionalidadeHelper
    {
        public static List<SelectListItem> paisesSelectList => new List<SelectListItem>()
        {
            new SelectListItem() {Text = "Brasil", Value = "Brasil"},
            new SelectListItem() {Text = "Afeganistão", Value = "Afeganistão"},
            new SelectListItem() {Text = "África do Sul", Value = "África do Sul"},
            new SelectListItem() {Text = "Albânia", Value = "Albânia"},
            new SelectListItem() {Text = "Alemanha", Value = "Alemanha"},
            new SelectListItem() {Text = "Andorra", Value = "Andorra"},
            new SelectListItem() {Text = "Angola", Value = "Angola"},
            new SelectListItem() {Text = "Anguilla", Value = "Anguilla"},
            new SelectListItem() {Text = "Antilhas Holandesas", Value = "Antilhas Holandesas"},
            new SelectListItem() {Text = "Antárctida", Value = "Antárctida"},
            new SelectListItem() {Text = "Antígua e Barbuda", Value = "Antígua e Barbuda"},
            new SelectListItem() {Text = "Argentina", Value = "Argentina"},
            new SelectListItem() {Text = "Argélia", Value = "Argélia"},
            new SelectListItem() {Text = "Armênia", Value = "Armênia"},
            new SelectListItem() {Text = "Aruba", Value = "Aruba"},
            new SelectListItem() {Text = "Arábia Saudita", Value = "Arábia Saudita"},
            new SelectListItem() {Text = "Austrália", Value = "Austrália"},
            new SelectListItem() {Text = "Áustria", Value = "Áustria"},
            new SelectListItem() {Text = "Azerbaijão", Value = "Azerbaijão"},
            new SelectListItem() {Text = "Bahamas", Value = "Bahamas"},
            new SelectListItem() {Text = "Bahrein", Value = "Bahrein"},
            new SelectListItem() {Text = "Bangladesh", Value = "Bangladesh"},
            new SelectListItem() {Text = "Barbados", Value = "Barbados"},
            new SelectListItem() {Text = "Belize", Value = "Belize"},
            new SelectListItem() {Text = "Benim", Value = "Benim"},
            new SelectListItem() {Text = "Bermudas", Value = "Bermudas"},
            new SelectListItem() {Text = "Bielorrússia", Value = "Bielorrússia"},
            new SelectListItem() {Text = "Bolívia", Value = "Bolívia"},
            new SelectListItem() {Text = "Botswana", Value = "Botswana"},
            new SelectListItem() {Text = "Brunei", Value = "Brunei"},
            new SelectListItem() {Text = "Bulgária", Value = "Bulgária"},
            new SelectListItem() {Text = "Burkina Faso", Value = "Burkina Faso"},
            new SelectListItem() {Text = "Burundi", Value = "Burundi"},
            new SelectListItem() {Text = "Butão", Value = "Butão"},
            new SelectListItem() {Text = "Bélgica", Value = "Bélgica"},
            new SelectListItem() {Text = "Bósnia e Herzegovina", Value = "Bósnia e Herzegovina"},
            new SelectListItem() {Text = "Cabo Verde", Value = "Cabo Verde"},
            new SelectListItem() {Text = "Camarões", Value = "Camarões"},
            new SelectListItem() {Text = "Camboja", Value = "Camboja"},
            new SelectListItem() {Text = "Canadá", Value = "Canadá"},
            new SelectListItem() {Text = "Catar", Value = "Catar"},
            new SelectListItem() {Text = "Cazaquistão", Value = "Cazaquistão"},
            new SelectListItem() {Text = "Chade", Value = "Chade"},
            new SelectListItem() {Text = "Chile", Value = "Chile"},
            new SelectListItem() {Text = "China", Value = "China"},
            new SelectListItem() {Text = "Chipre", Value = "Chipre"},
            new SelectListItem() {Text = "Colômbia", Value = "Colômbia"},
            new SelectListItem() {Text = "Comores", Value = "Comores"},
            new SelectListItem() {Text = "Coreia do Norte", Value = "Coreia do Norte"},
            new SelectListItem() {Text = "Coreia do Sul", Value = "Coreia do Sul"},
            new SelectListItem() {Text = "Costa do Marfim", Value = "Costa do Marfim"},
            new SelectListItem() {Text = "Costa Rica", Value = "Costa Rica"},
            new SelectListItem() {Text = "Croácia", Value = "Croácia"},
            new SelectListItem() {Text = "Cuba", Value = "Cuba"},
            new SelectListItem() {Text = "Dinamarca", Value = "Dinamarca"},
            new SelectListItem() {Text = "Djibouti", Value = "Djibouti"},
            new SelectListItem() {Text = "Dominica", Value = "Dominica"},
            new SelectListItem() {Text = "Egito", Value = "Egito"},
            new SelectListItem() {Text = "El Salvador", Value = "El Salvador"},
            new SelectListItem() {Text = "Emirados Árabes Unidos", Value = "Emirados Árabes Unidos"},
            new SelectListItem() {Text = "Equador", Value = "Equador"},
            new SelectListItem() {Text = "Eritreia", Value = "Eritreia"},
            new SelectListItem() {Text = "Escócia", Value = "Escócia"},
            new SelectListItem() {Text = "Eslováquia", Value = "Eslováquia"},
            new SelectListItem() {Text = "Eslovênia", Value = "Eslovênia"},
            new SelectListItem() {Text = "Espanha", Value = "Espanha"},
            new SelectListItem() {Text = "Estados Federados da Micronésia", Value = "Estados Federados da Micronésia"},
            new SelectListItem() {Text = "Estados Unidos", Value = "Estados Unidos"},
            new SelectListItem() {Text = "Estônia", Value = "Estônia"},
            new SelectListItem() {Text = "Etiópia", Value = "Etiópia"},
            new SelectListItem() {Text = "Fiji", Value = "Fiji"},
            new SelectListItem() {Text = "Filipinas", Value = "Filipinas"},
            new SelectListItem() {Text = "Finlândia", Value = "Finlândia"},
            new SelectListItem() {Text = "França", Value = "França"},
            new SelectListItem() {Text = "Gabão", Value = "Gabão"},
            new SelectListItem() {Text = "Gana", Value = "Gana"},
            new SelectListItem() {Text = "Geórgia", Value = "Geórgia"},
            new SelectListItem() {Text = "Gibraltar", Value = "Gibraltar"},
            new SelectListItem() {Text = "Granada", Value = "Granada"},
            new SelectListItem() {Text = "Gronelândia", Value = "Gronelândia"},
            new SelectListItem() {Text = "Grécia", Value = "Grécia"},
            new SelectListItem() {Text = "Guadalupe", Value = "Guadalupe"},
            new SelectListItem() {Text = "Guam", Value = "Guam"},
            new SelectListItem() {Text = "Guatemala", Value = "Guatemala"},
            new SelectListItem() {Text = "Guernesei", Value = "Guernesei"},
            new SelectListItem() {Text = "Guiana", Value = "Guiana"},
            new SelectListItem() {Text = "Guiana Francesa", Value = "Guiana Francesa"},
            new SelectListItem() {Text = "Guiné", Value = "Guiné"},
            new SelectListItem() {Text = "Guiné Equatorial", Value = "Guiné Equatorial"},
            new SelectListItem() {Text = "Guiné-Bissau", Value = "Guiné-Bissau"},
            new SelectListItem() {Text = "Gâmbia", Value = "Gâmbia"},
            new SelectListItem() {Text = "Haiti", Value = "Haiti"},
            new SelectListItem() {Text = "Honduras", Value = "Honduras"},
            new SelectListItem() {Text = "Hong Kong", Value = "Hong Kong"},
            new SelectListItem() {Text = "Hungria", Value = "Hungria"},
            new SelectListItem() {Text = "Ilha Bouvet", Value = "Ilha Bouvet"},
            new SelectListItem() {Text = "Ilha de Man", Value = "Ilha de Man"},
            new SelectListItem() {Text = "Ilha do Natal", Value = "Ilha do Natal"},
            new SelectListItem() {Text = "Ilha Heard e Ilhas McDonald", Value = "Ilha Heard e Ilhas McDonald"},
            new SelectListItem() {Text = "Ilha Norfolk", Value = "Ilha Norfolk"},
            new SelectListItem() {Text = "Ilhas Cayman", Value = "Ilhas Cayman"},
            new SelectListItem() {Text = "Ilhas Cocos (Keeling", Value = "Ilhas Cocos (Keeling"},
            new SelectListItem() {Text = "Ilhas Cook", Value = "Ilhas Cook"},
            new SelectListItem() {Text = "Ilhas Feroé", Value = "Ilhas Feroé"},
            new SelectListItem() {Text = "Ilhas Geórgia do Sul e Sandwich do Sul", Value = "Ilhas Geórgia do Sul e Sandwich do Sul"},
            new SelectListItem() {Text = "Ilhas Malvinas", Value = "Ilhas Malvinas"},
            new SelectListItem() {Text = "Ilhas Marshall", Value = "Ilhas Marshall"},
            new SelectListItem() { Text = "Ilhas Menores Distantes dos Estados Unidos", Value = "Ilhas Menores Distantes dos Estados Unidos"},
            new SelectListItem() {Text = "Ilhas Salomão", Value = "Ilhas Salomão"},
            new SelectListItem() {Text = "Ilhas Virgens Americanas", Value = "Ilhas Virgens Americanas"},
            new SelectListItem() {Text = "Ilhas Virgens Britânicas", Value = "Ilhas Virgens Britânicas"},
            new SelectListItem() {Text = "Ilhas Åland", Value = "Ilhas Åland"},
            new SelectListItem() {Text = "Indonésia", Value = "Indonésia"},
            new SelectListItem() {Text = "Inglaterra", Value = "Inglaterra"},
            new SelectListItem() {Text = "Índia", Value = "Índia"},
            new SelectListItem() {Text = "Iraque", Value = "Iraque"},
            new SelectListItem() {Text = "Irlanda do Norte", Value = "Irlanda do Norte"},
            new SelectListItem() {Text = "Irlanda", Value = "Irlanda"},
            new SelectListItem() {Text = "Irã", Value = "Irã"},
            new SelectListItem() {Text = "Islândia", Value = "Islândia"},
            new SelectListItem() {Text = "Israel", Value = "Israel"},
            new SelectListItem() {Text = "Itália", Value = "Itália"},
            new SelectListItem() {Text = "Iêmen", Value = "Iêmen"},
            new SelectListItem() {Text = "Jamaica", Value = "Jamaica"},
            new SelectListItem() {Text = "Japão", Value = "Japão"},
            new SelectListItem() {Text = "Jersey", Value = "Jersey"},
            new SelectListItem() {Text = "Jordânia", Value = "Jordânia"},
            new SelectListItem() {Text = "Kiribati", Value = "Kiribati"},
            new SelectListItem() {Text = "Kuwait", Value = "Kuwait"},
            new SelectListItem() {Text = "Laos", Value = "Laos"},
            new SelectListItem() {Text = "Lesoto", Value = "Lesoto"},
            new SelectListItem() {Text = "Letônia", Value = "Letônia"},
            new SelectListItem() {Text = "Libéria", Value = "Libéria"},
            new SelectListItem() {Text = "Liechtenstein", Value = "Liechtenstein"},
            new SelectListItem() {Text = "Lituânia", Value = "Lituânia"},
            new SelectListItem() {Text = "Luxemburgo", Value = "Luxemburgo"},
            new SelectListItem() {Text = "Líbano", Value = "Líbano"},
            new SelectListItem() {Text = "Líbia", Value = "Líbia"},
            new SelectListItem() {Text = "Macau", Value = "Macau"},
            new SelectListItem() {Text = "Macedônia", Value = "Macedônia"},
            new SelectListItem() {Text = "Madagáscar", Value = "Madagáscar"},
            new SelectListItem() {Text = "Malawi", Value = "Malawi"},
            new SelectListItem() {Text = "Maldivas", Value = "Maldivas"},
            new SelectListItem() {Text = "Mali", Value = "Mali"},
            new SelectListItem() {Text = "Malta", Value = "Malta"},
            new SelectListItem() {Text = "Malásia", Value = "Malásia"},
            new SelectListItem() {Text = "Marianas Setentrionais", Value = "Marianas Setentrionais"},
            new SelectListItem() {Text = "Marrocos", Value = "Marrocos"},
            new SelectListItem() {Text = "Martinica", Value = "Martinica"},
            new SelectListItem() {Text = "Mauritânia", Value = "Mauritânia"},
            new SelectListItem() {Text = "Maurícia", Value = "Maurícia"},
            new SelectListItem() {Text = "Mayotte", Value = "Mayotte"},
            new SelectListItem() {Text = "Moldávia", Value = "Moldávia"},
            new SelectListItem() {Text = "Mongólia", Value = "Mongólia"},
            new SelectListItem() {Text = "Montenegro", Value = "Montenegro"},
            new SelectListItem() {Text = "Montserrat", Value = "Montserrat"},
            new SelectListItem() {Text = "Moçambique", Value = "Moçambique"},
            new SelectListItem() {Text = "Myanmar", Value = "Myanmar"},
            new SelectListItem() {Text = "México", Value = "México"},
            new SelectListItem() {Text = "Mônaco", Value = "Mônaco"},
            new SelectListItem() {Text = "Namíbia", Value = "Namíbia"},
            new SelectListItem() {Text = "Nauru", Value = "Nauru"},
            new SelectListItem() {Text = "Nepal", Value = "Nepal"},
            new SelectListItem() {Text = "Nicarágua", Value = "Nicarágua"},
            new SelectListItem() {Text = "Nigéria", Value = "Nigéria"},
            new SelectListItem() {Text = "Niue", Value = "Niue"},
            new SelectListItem() {Text = "Noruega", Value = "Noruega"},
            new SelectListItem() {Text = "Nova Caledônia", Value = "Nova Caledônia"},
            new SelectListItem() {Text = "Nova Zelândia", Value = "Nova Zelândia"},
            new SelectListItem() {Text = "Níger", Value = "Níger"},
            new SelectListItem() {Text = "Omã", Value = "Omã"},
            new SelectListItem() {Text = "Palau", Value = "Palau"},
            new SelectListItem() {Text = "Palestina", Value = "Palestina"},
            new SelectListItem() {Text = "Panamá", Value = "Panamá"},
            new SelectListItem() {Text = "Papua-Nova Guiné", Value = "Papua-Nova Guiné"},
            new SelectListItem() {Text = "Paquistão", Value = "Paquistão"},
            new SelectListItem() {Text = "Paraguai", Value = "Paraguai"},
            new SelectListItem() {Text = "País de Gales", Value = "País de Gales"},
            new SelectListItem() {Text = "Países Baixos", Value = "Países Baixos"},
            new SelectListItem() {Text = "Peru", Value = "Peru"},
            new SelectListItem() {Text = "Pitcairn", Value = "Pitcairn"},
            new SelectListItem() {Text = "Polinésia Francesa", Value = "Polinésia Francesa"},
            new SelectListItem() {Text = "Polônia", Value = "Polônia"},
            new SelectListItem() {Text = "Porto Rico", Value = "Porto Rico"},
            new SelectListItem() {Text = "Portugal", Value = "Portugal"},
            new SelectListItem() {Text = "Quirguistão", Value = "Quirguistão"},
            new SelectListItem() {Text = "Quênia", Value = "Quênia"},
            new SelectListItem() {Text = "Reino Unido", Value = "Reino Unido"},
            new SelectListItem() {Text = "República Centro-Africana", Value = "República Centro-Africana"},
            new SelectListItem() {Text = "República Checa", Value = "República Checa"},
            new SelectListItem() {Text = "República Democrática do Congo", Value = "República Democrática do Congo"},
            new SelectListItem() {Text = "República do Congo", Value = "República do Congo"},
            new SelectListItem() {Text = "República Dominicana", Value = "República Dominicana"},
            new SelectListItem() {Text = "Reunião", Value = "Reunião"},
            new SelectListItem() {Text = "Romênia", Value = "Romênia"},
            new SelectListItem() {Text = "Ruanda", Value = "Ruanda"},
            new SelectListItem() {Text = "Rússia", Value = "Rússia"},
            new SelectListItem() {Text = "Saara Ocidental", Value = "Saara Ocidental"},
            new SelectListItem() {Text = "Saint Martin", Value = "Saint Martin"},
            new SelectListItem() {Text = "Saint-Barthélemy", Value = "Saint-Barthélemy"},
            new SelectListItem() {Text = "Saint-Pierre e Miquelon", Value = "Saint-Pierre e Miquelon"},
            new SelectListItem() {Text = "Samoa Americana", Value = "Samoa Americana"},
            new SelectListItem() {Text = "Samoa", Value = "Samoa"},
            new SelectListItem() { Text = "Santa Helena, Ascensão e Tristão da Cunha", Value = "Santa Helena, Ascensão e Tristão da Cunha" },
            new SelectListItem() {Text = "Santa Lúcia", Value = "Santa Lúcia"},
            new SelectListItem() {Text = "Senegal", Value = "Senegal"},
            new SelectListItem() {Text = "Serra Leoa", Value = "Serra Leoa"},
            new SelectListItem() {Text = "Seychelles", Value = "Seychelles"},
            new SelectListItem() {Text = "Singapura", Value = "Singapura"},
            new SelectListItem() {Text = "Somália", Value = "Somália"},
            new SelectListItem() {Text = "Sri Lanka", Value = "Sri Lanka"},
            new SelectListItem() {Text = "Suazilândia", Value = "Suazilândia"},
            new SelectListItem() {Text = "Sudão", Value = "Sudão"},
            new SelectListItem() {Text = "Suriname", Value = "Suriname"},
            new SelectListItem() {Text = "Suécia", Value = "Suécia"},
            new SelectListItem() {Text = "Suíça", Value = "Suíça"},
            new SelectListItem() {Text = "Svalbard e Jan Mayen", Value = "Svalbard e Jan Mayen"},
            new SelectListItem() {Text = "São Cristóvão e Nevis", Value = "São Cristóvão e Nevis"},
            new SelectListItem() {Text = "São Marino", Value = "São Marino"},
            new SelectListItem() {Text = "São Tomé e Príncipe", Value = "São Tomé e Príncipe"},
            new SelectListItem() {Text = "São Vicente e Granadinas", Value = "São Vicente e Granadinas"},
            new SelectListItem() {Text = "Sérvia", Value = "Sérvia"},
            new SelectListItem() {Text = "Síria", Value = "Síria"},
            new SelectListItem() {Text = "Tadjiquistão", Value = "Tadjiquistão"},
            new SelectListItem() {Text = "Tailândia", Value = "Tailândia"},
            new SelectListItem() {Text = "Taiwan", Value = "Taiwan"},
            new SelectListItem() {Text = "Tanzânia", Value = "Tanzânia"},
            new SelectListItem() { Text = "Terras Austrais e Antárticas Francesas", Value = "Terras Austrais e Antárticas Francesas"},
            new SelectListItem() { Text = "Território Britânico do Oceano Índico", Value = "Território Britânico do Oceano Índico"},
            new SelectListItem() {Text = "Timor-Leste", Value = "Timor-Leste"},
            new SelectListItem() {Text = "Togo", Value = "Togo"},
            new SelectListItem() {Text = "Tonga", Value = "Tonga"},
            new SelectListItem() {Text = "Toquelau", Value = "Toquelau"},
            new SelectListItem() {Text = "Trinidad e Tobago", Value = "Trinidad e Tobago"},
            new SelectListItem() {Text = "Tunísia", Value = "Tunísia"},
            new SelectListItem() {Text = "Turcas e Caicos", Value = "Turcas e Caicos"},
            new SelectListItem() {Text = "Turquemenistão", Value = "Turquemenistão"},
            new SelectListItem() {Text = "Turquia", Value = "Turquia"},
            new SelectListItem() {Text = "Tuvalu", Value = "Tuvalu"},
            new SelectListItem() {Text = "Ucrânia", Value = "Ucrânia"},
            new SelectListItem() {Text = "Uganda", Value = "Uganda"},
            new SelectListItem() {Text = "Uruguai", Value = "Uruguai"},
            new SelectListItem() {Text = "Uzbequistão", Value = "Uzbequistão"},
            new SelectListItem() {Text = "Vanuatu", Value = "Vanuatu"},
            new SelectListItem() {Text = "Vaticano", Value = "Vaticano"},
            new SelectListItem() {Text = "Venezuela", Value = "Venezuela"},
            new SelectListItem() {Text = "Vietname", Value = "Vietname"},
            new SelectListItem() {Text = "Wallis e Futuna", Value = "Wallis e Futuna"},
            new SelectListItem() {Text = "Zimbabwe", Value = "Zimbabwe"},
            new SelectListItem() {Text = "Zâmbia", Value = "Zâmbia"}
        };

        public static List<SelectListItem> estadosBrasil => new List<SelectListItem>()
        {
            new SelectListItem() {Text = "AC", Value = "AC"},
            new SelectListItem() {Text = "AL", Value = "AL"},
            new SelectListItem() {Text = "AP", Value = "AP"},
            new SelectListItem() {Text = "AM", Value = "AM"},
            new SelectListItem() {Text = "BA", Value = "BA"},
            new SelectListItem() {Text = "CE", Value = "CE"},
            new SelectListItem() {Text = "DF", Value = "DF"},
            new SelectListItem() {Text = "ES", Value = "ES"},
            new SelectListItem() {Text = "GO", Value = "GO"},
            new SelectListItem() {Text = "MA", Value = "MA"},
            new SelectListItem() {Text = "MS", Value = "MS"},
            new SelectListItem() {Text = "MT", Value = "MT"},
            new SelectListItem() {Text = "MG", Value = "MG"},
            new SelectListItem() {Text = "PA", Value = "PA"},
            new SelectListItem() {Text = "PB", Value = "PB"},
            new SelectListItem() {Text = "PR", Value = "PR"},
            new SelectListItem() {Text = "PE", Value = "PE"},
            new SelectListItem() {Text = "PI", Value = "PI"},
            new SelectListItem() {Text = "RJ", Value = "RJ"},
            new SelectListItem() {Text = "RN", Value = "RN"},
            new SelectListItem() {Text = "RS", Value = "RS"},
            new SelectListItem() {Text = "RO", Value = "RO"},
            new SelectListItem() {Text = "RR", Value = "RR"},
            new SelectListItem() {Text = "SC", Value = "SC"},
            new SelectListItem() {Text = "SP", Value = "SP"},
            new SelectListItem() {Text = "SE", Value = "SE"},
            new SelectListItem() {Text = "TO", Value = "TO"}
        };
    };


    var estadosSelectList = ...NacionalidadeHelper.estadosBrasil;
    var paisesSelectList = ...NacionalidadeHelper.paisesSelectList;

    @Html.LabelFor(model => model.Pais, new { @class = "control-label" })<br />
    @Html.DropDownList("Pais", paisesSelectList, new {@class = "form-control"})
    @Html.ValidationMessageFor(model => model.Pais)

    @Html.LabelFor(model => model.Estado, new { @class = "control-label" })
    @Html.DropDownListFor(model => model.Estado, estadosSelectList, "Selecione", new { @class = "form-control" })
    @Html.ValidationMessageFor(model => model.Estado)
